### PR TITLE
Update dependencies to latest version

### PR DESCRIPTION
**Pull request by gaetandezeiraud**

### CODE REVIEW

**Comment by m-gagne** [comment]
Thanks for the PR @Brouilles! I would not have thought anyone was using this anymore =)

**Comment by Brouilles** [comment]
Useful to automate the generation of Microsoft Store images (UWP or msix). Thanks for the creation of this package!

**Comment by gaetandezeiraud** [comment]
Hope you can update the package on npm soon! https://www.npmjs.com/package/svg2uwptiles

**Comment by m-gagne** [comment]
Done. As I have not been actively developing for quite some time, would be happy to add you as a contributor/owner to this project.

**Comment by gaetandezeiraud** [comment]
Like you want! I don't think a lot of maintenance is necessary. Except a small fix for the default canvas path (don't get it from the node_modules folder when the package is a dependency).

**Pull request merged**
